name: Build with bob

on: [push, pull_request]

jobs:
  build:
    uses: defold/github-actions-common/.github/workflows/bob.yml@master
    with:
      channel: beta
      build_server: https://build-stage.defold.com
